# .streamlit/secrets.toml
# won't .gitignore this file; private github repo used
# points to pg on a heroku free instance rog@gatech.edu setup

[postgres]
host = "ec2-52-204-72-14.compute-1.amazonaws.com"
port = 5432
dbname = "d6bl2ehgovce4p"
user = "xidaevojxqrizh"
password = "684801422d3447f183f155537a94161dc7df32d15883034ca77fda081411fe27"
